### ISSUE TITLE
testrpc support? 

### ISSUE THREAD

**Issue by rstormsf** [gobitfly/etherchain-light#18] opened 2017-08-03 00:15 UTC
I switched from IPC to Http Provider - works fine, but https://github.com/ethereumjs/testrpc/issues/363

**Comment by ppratscher** [comment] 2017-09-03 19:17
Could you please elaborate on the use case for connecting the explorer to a testrpc instance? As the issue is more related to testrpc than etherchain-light I will close it for now.

**Closed by ppratscher** 2017-09-03 19:17 UTC
